version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/sociamidev/
hooks:
  BeforeInstall:
    - location: deploy/clean_old_build
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: deploy/copy_sourcecode
      timeout: 3000
      runas: ec2-user
  ApplicationStart:
    - location: deploy/start_server
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: deploy/stop_server
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: deploy/validate
      timeout: 60
      runas: ec2-user
